### ISSUE TITLE
gadm polygons to geojson

### ISSUE THREAD

**Issue by Ohm-Np** [pratik-tan10/Python#1]
Hi @pratik-tan10, 

First of all I would like to thank you for creating this repository and making it public. I hope to learn more geo-python based problem solving skills. 

For now, if its possible could you do something on python which would help us get access to the GADM polygons and for a sample polygon (say Myagdi), convert it to geojson and write it in file. I would also like to get involved in some time.

**Comment by pratik-tan10** [comment]
Hi @Ohm-Np,
Thank you for your encouragement. I did the thing you asked me to do. Of course, that code can be made way more compact and efficient, but I hope that gives some idea.

**Comment by Ohm-Np** [comment]
Also, could you tell me the the file-name where you have the script for this task?
