### ISSUE TITLE
R - Python link up 

### ISSUE THREAD

**Issue by Ohm-Np** [pratik-tan10/Python#2]
Hi Pratik! I am planning to write an article targeting GIS beginners at two different phases:
1. Vector data processing in **R**
2. Raster data processing in **R**

For the vector data processing, I have thought of including following processing tasks:

- [x] GADM data download
- [x] download open-access vector data (as target data)
- [x] projecting both polygons to same CRS
- [x] subset the data - for region of interest (roi)
- [x] create buffer-zone around the roi
- [x] crop target data using roi
- [x] compute area of the target data using roi

Similarly, there could be some other geoprocessing tasks that we could simply reproduce in any devices with the scripts that we write. It would be great if you could suggest some of those tasks which you think might be useful. Feel free to add the tasks and you can change the order of the tasks if you want. 

Also, it would be great if you could replicate the same tasks using **Python** so that we can have two different articles with same data, same geo-processing steps but with two different programming languages. That would be cool. And later at some point of time, we could proceed with the raster processing - parallelly with R & Python. What do you think?

**Comment by pratik-tan10** [comment]
That would be great. A good addition will be a simple map plot of extracted data. I would need some clarification on the intended difference between the subset and crop functionalities.

**Comment by Ohm-Np** [comment]
I am going to add some terminoloies and their definitions here to make things clearer (for anyone who might come later here to see the chat)

**subset**
Imagine you have a whole polygon of Nepal and you want to only take the polygon for Kathmandu district, that time we would need to apply subset or simply filter technique which is pretty easier in R, but for python I am not sure how it is done.

**crop**
Geometrical intersection between two polygons

**target data** & **roi**
for e.g. I want to see how many buildings are there in the Kathmandu district, so I need data from OSM about buildings. In this case, osm data would be the _target data_ & the polygon of Kathmandu district would be my _roi_.

**Comment by pratik-tan10** [comment]
Great.
